[package]
name = "wan-failover-mikrotik"
version = "1.0.0"
edition = "2024"

[dependencies]
ssh2 = { version = "0.9.5", features = ["vendored-openssl"] }
openssl = { version = "0.10.74", features = ["vendored"] }

[build-dependencies]
dotenv-build = "0.1.1"
